version: 1.0.{build}
build_script:
- cmd: build.bat
artifacts:
- path: *.jar
  name: demo
deploy:
- provider: GitHub
  auth_token:
    secure: icaJlPkqzI3IUxSqUHgI34BtCpffDWxpp4otuYUAwA1RqMtQvAtdmXjOL9UOdqQI
  artifact: /.+\.jar/