version: 0.0.0.{build}
skip_tags: true
build_script:
- cmd: build.bat
artifacts:
- path: .\*.jar
  name: demo
deploy:
- provider: GitHub
  auth_token:
    secure: crzVFlTyFurgbVImysXO1iQMlguXxkrJHgHoK0M9nkf5d2dboy1bGS4OwENIPT69
  artifact: /.+\.jar/
notifications:
- provider: Email
  to:
  - wazcd_1608@qq.com
  - 850781307@qq.com
  - 2308574548@qq.com
  - 957154990@qq.com
  subject: Build status of Room
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false