version: 1.0.{build}
build_script:
- cmd: build.bat
artifacts:
- path: *.jar
  name: demo
deploy:
- provider: GitHub
  auth_token:
    secure: D/3LJCvnQzb2LT6rtq7KCPZcyW4fCmh9S0zJw4jsxGLRLSPRMaIdmd2iw/Yri+vT
  artifact: /.+\.jar/